// Generated by scripts/sync-framework-versions.mjs. Do not edit manually.

export interface FrameworkDependencyVersions {
  elfui: string;
  vitePlugin: string;
  router: string;
  chain: string;
}

export const frameworkDependencyVersions: FrameworkDependencyVersions = {
  elfui: "^0.1.0-beta.0",
  vitePlugin: "^0.1.0-beta.0",
  router: "^0.1.0-beta.0",
  chain: "^0.1.0-beta.0"
};
