// Generated by scripts/sync-framework-versions.mjs. Do not edit manually.

export interface FrameworkDependencyVersions {
  core: string;
  vitePlugin: string;
  router: string;
  chain: string;
}

export const frameworkDependencyVersions: FrameworkDependencyVersions = {
  core: "0.1.0-beta.21",
  vitePlugin: "0.1.0-beta.21",
  router: "0.1.0-beta.12",
  chain: "0.1.0-beta.3",
};
